CREATE TABLE [dbo].[Daily_POS_Headers] (
    [File_ID]                            NVARCHAR (1000) NULL,
    [FileRowNumber]                      BIGINT          NULL,
    [From_FileRowNumber]                 BIGINT          NULL,
    [POSDocumentHeaderID]                BIGINT          NULL,
    [POSDocumentHeaderCode]              NVARCHAR (1000) NULL,
    [POSReceiptNumber]                   BIGINT          NULL,
    [SiteCode]                           NVARCHAR (1000) NULL,
    [ShiftCode]                          NVARCHAR (1000) NULL,
    [DocumentTypeCode]                   NVARCHAR (1000) NULL,
    [TransactionStartTimestamp]          DATETIME2 (7)   NULL,
    [TransactionStartDateID]             BIGINT          NULL,
    [TransactionStartTimeID]             BIGINT          NULL,
    [TransactionEndTimestamp]            DATETIME2 (7)   NULL,
    [TotalDiscountValue]                 REAL            NULL,
    [TotalTaxValue]                      REAL            NULL,
    [TotalValue]                         REAL            NULL,
    [POSMachineCode]                     NVARCHAR (1000) NULL,
    [CustomerName]                       NVARCHAR (1000) NULL,
    [CustomerTelephone]                  NVARCHAR (1000) NULL,
    [CustomerAddress]                    NVARCHAR (1000) NULL,
    [HeaderPromotionalDiscountIndicator] BIT             NULL,
    [ResourceCodeCashier]                NVARCHAR (1000) NULL,
    [ResourceCodeHeaderApprovedBy]       NVARCHAR (1000) NULL,
    [FundNumberID]                       BIGINT          NULL,
    [RecieptDurationInSecond]            REAL            NULL,
    [ReceiptTotalAmountRangeID]          BIGINT          NULL,
    [TotalBeforeTenderTimeStamp]         DATETIME        NULL,
    [OriginalReceiptCode]                NVARCHAR (1000) NULL,
    [IsPayedCash]                        BIT             NULL,
    [AttributeHeaderInt1]                BIGINT          NULL,
    [AttributeHeaderInt2]                BIGINT          NULL,
    [AttributeHeaderInt3]                BIGINT          NULL,
    [AttributeHeaderInt4]                BIGINT          NULL,
    [AttributeHeaderInt5]                BIGINT          NULL,
    [AttributeHeaderBit1]                BIT             NULL,
    [AttributeHeaderBit2]                BIT             NULL,
    [AttributeHeaderBit3]                BIT             NULL,
    [AttributeHeaderBit4]                BIT             NULL,
    [AttributeHeaderBit5]                BIT             NULL,
    [AttributeHeaderBit6]                BIT             NULL,
    [AttributeHeaderBit7]                BIT             NULL,
    [AttributeHeaderBit8]                BIT             NULL,
    [AttributeHeaderBit9]                BIT             NULL,
    [AttributeHeaderBit10]               NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode1]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode2]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode3]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode4]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode5]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode6]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode7]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode8]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode9]          NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode10]         NVARCHAR (1000) NULL,
    [TimeBetweenReceiptsInSecond]        REAL            NULL,
    [TotalItemQuantity]                  REAL            NULL,
    [FileKey]                            NVARCHAR (1000) NULL,
    [TotalVoidRefundAmount]              REAL            NULL,
    [RingDurationInSecond]               REAL            NULL,
    [TenderDurationInSecond]             REAL            NULL,
    [AttributeHeaderBit11]               BIT             NULL,
    [AttributeHeaderBit12]               BIT             NULL,
    [AttributeHeaderBit13]               BIT             NULL,
    [AttributeHeaderBit14]               BIT             NULL,
    [AttributeHeaderBit15]               BIT             NULL,
    [AttributeHeaderBit16]               BIT             NULL,
    [AttributeHeaderBit17]               BIT             NULL,
    [AttributeHeaderBit18]               BIT             NULL,
    [AttributeHeaderBit19]               BIT             NULL,
    [AttributeHeaderBit20]               BIT             NULL,
    [AttributeHeaderBIGINT6]             BIGINT          NULL,
    [AttributeHeaderBIGINT7]             BIGINT          NULL,
    [AttributeHeaderBIGINT8]             BIGINT          NULL,
    [AttributeHeaderBIGINT9]             BIGINT          NULL,
    [AttributeHeaderBIGINT10]            BIGINT          NULL,
    [AttributeGroupHeaderCode11]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode12]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode13]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode14]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode15]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode16]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode17]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode18]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode19]         NVARCHAR (1000) NULL,
    [AttributeGroupHeaderCode20]         NVARCHAR (1000) NULL,
    [TotalWithoutTax]                    REAL            NULL,
    [DateTime_Added]                     NVARCHAR (1000) NOT NULL
);

