CREATE TABLE [dbo].[Daily_SaleLevel] (
    [File_ID]                                NVARCHAR (1000) NULL,
    [FileRowNumber]                          BIGINT          NULL,
    [SiteCode]                               NVARCHAR (1000) NULL,
    [DocumentDate]                           DATETIME2 (7)   NULL,
    [ProductCode]                            NVARCHAR (1000) NULL,
    [ItemQuantity]                           REAL            NULL,
    [ItemCost]                               REAL            NULL,
    [ItemRetail]                             REAL            NULL,
    [UpdateDate]                             DATETIME2 (7)   NULL,
    [DirectionIN]                            BIT             NULL,
    [DirectionOUT]                           BIT             NULL,
    [FirstProductSaleDateTime]               DATETIME2 (7)   NULL,
    [LastProductSaleDateTime]                DATETIME2 (7)   NULL,
    [VendorCode]                             NVARCHAR (1000) NULL,
    [CostAmount]                             REAL            NULL,
    [RetailAmount]                           REAL            NULL,
    [FirstProductSaleFromOpenHoursInminutes] BIGINT          NULL,
    [OpenHoursInMinutes]                     BIGINT          NULL,
    [AttributeInt1]                          BIGINT          NULL,
    [AttributeInt2]                          BIGINT          NULL,
    [AttributeInt3]                          BIGINT          NULL,
    [AttributeInt4]                          BIGINT          NULL,
    [AttributeInt5]                          BIGINT          NULL,
    [AttributeBit1]                          BIT             NULL,
    [AttributeBit2]                          BIT             NULL,
    [AttributeBit3]                          BIT             NULL,
    [AttributeBit4]                          BIT             NULL,
    [AttributeBit5]                          BIT             NULL,
    [AttributeBit6]                          BIT             NULL,
    [AttributeBit7]                          BIT             NULL,
    [AttributeBit8]                          BIT             NULL,
    [AttributeBit9]                          BIT             NULL,
    [AttributeBit10]                         BIT             NULL,
    [AttributeGroupCode1]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode2]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode3]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode4]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode5]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode6]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode7]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode8]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode9]                    NVARCHAR (1000) NULL,
    [AttributeGroupCode10]                   NVARCHAR (1000) NULL,
    [FileKey]                                NVARCHAR (2000) NULL,
    [UOM]                                    REAL            NULL,
    [CustomCode]                             NVARCHAR (1000) NULL,
    [Measure1]                               REAL            NULL,
    [Measure2]                               REAL            NULL,
    [Measure3]                               REAL            NULL,
    [Measure4]                               REAL            NULL,
    [Measure5]                               REAL            NULL,
    [Measure6]                               REAL            NULL,
    [Measure7]                               REAL            NULL,
    [Measure8]                               REAL            NULL,
    [Measure9]                               REAL            NULL,
    [Measure10]                              REAL            NULL,
    [DateTime_Added]                         NVARCHAR (1000) NOT NULL,
    [HashValue]                              NVARCHAR (1000) NULL
);

