CREATE TABLE [dbo].[Daily_POS_Tenders] (
    [File_ID]                               NVARCHAR (1000) NULL,
    [POSDocumentHeaderID]                   BIGINT          NULL,
    [POSDocumentHeaderCode]                 NVARCHAR (1000) NOT NULL,
    [TenderTypeCode]                        NVARCHAR (1000) NOT NULL,
    [ApprovedByResourceCode]                NVARCHAR (1000) NULL,
    [SiteCode]                              NVARCHAR (1000) NOT NULL,
    [ShiftCode]                             NVARCHAR (1000) NOT NULL,
    [ResourceCodeCashier]                   NVARCHAR (1000) NOT NULL,
    [ScannedTimeStamp]                      DATETIME2 (7)   NOT NULL,
    [CreditCardNumber]                      NVARCHAR (1000) NULL,
    [CreditCardOwner]                       NVARCHAR (1000) NULL,
    [PaymentTotal]                          REAL            NULL,
    [ManuallyTypedIndicator]                BIT             NULL,
    [CreditCardOfflineTransactionIndicator] BIT             NULL,
    [ScannedDateId]                         BIGINT          NOT NULL,
    [ScannedTimeID]                         BIGINT          NOT NULL,
    [TenderCode]                            NVARCHAR (1000) NOT NULL,
    [CreditCardNumberIDCode]                NVARCHAR (1000) NULL,
    [FileKey]                               NVARCHAR (1000) NULL,
    [AttributeBit1]                         BIT             NULL,
    [AttributeBit2]                         BIT             NULL,
    [AttributeBit3]                         BIT             NULL,
    [AttributeBit4]                         BIT             NULL,
    [AttributeBit5]                         BIT             NULL,
    [AttributeGroupCode1]                   NVARCHAR (1000) NULL,
    [AttributeGroupCode2]                   NVARCHAR (1000) NULL,
    [AttributeGroupCode3]                   NVARCHAR (1000) NULL,
    [AttributeGroupCode4]                   NVARCHAR (1000) NULL,
    [AttributeGroupCode5]                   NVARCHAR (1000) NULL,
    [DateTime_Added]                        NVARCHAR (1000) NOT NULL
);

