CREATE TABLE [dbo].[Daily_Inventory_Header] (
    [File_ID]                       NVARCHAR (1000) NULL,
    [FileRowNumber]                 BIGINT          NULL,
    [InventoryHeaderCode]           NVARCHAR (1000) NULL,
    [DocumentDate]                  DATETIME2 (7)   NULL,
    [SiteCode]                      NVARCHAR (1000) NULL,
    [ValidatedBy]                   NVARCHAR (1000) NULL,
    [ApprovedBy]                    NVARCHAR (1000) NULL,
    [DocumentNumber]                NVARCHAR (1000) NULL,
    [DocumentTypeCode]              NVARCHAR (1000) NULL,
    [UpdateDate]                    DATETIME2 (7)   NULL,
    [InsertDate]                    DATETIME2 (7)   NULL,
    [InventoryCountFrequencyID]     BIGINT          NULL,
    [InventoryCountTypeByProductID] BIGINT          NULL,
    [AttributeInt1]                 BIGINT          NULL,
    [AttributeInt2]                 BIGINT          NULL,
    [AttributeInt3]                 BIGINT          NULL,
    [AttributeInt4]                 BIGINT          NULL,
    [AttributeInt5]                 BIGINT          NULL,
    [AttributeBit1]                 BIT             NULL,
    [AttributeBit2]                 BIT             NULL,
    [AttributeBit3]                 BIT             NULL,
    [AttributeBit4]                 BIT             NULL,
    [AttributeBit5]                 BIT             NULL,
    [AttributeBit6]                 BIT             NULL,
    [AttributeBit7]                 BIT             NULL,
    [AttributeBit8]                 BIT             NULL,
    [AttributeBit9]                 BIT             NULL,
    [AttributeBit10]                BIT             NULL,
    [AttributeGroupCode1]           NVARCHAR (1000) NULL,
    [AttributeGroupCode2]           NVARCHAR (1000) NULL,
    [AttributeGroupCode3]           NVARCHAR (1000) NULL,
    [AttributeGroupCode4]           NVARCHAR (1000) NULL,
    [AttributeGroupCode5]           NVARCHAR (1000) NULL,
    [AttributeGroupCode6]           NVARCHAR (1000) NULL,
    [AttributeGroupCode7]           NVARCHAR (1000) NULL,
    [AttributeGroupCode8]           NVARCHAR (1000) NULL,
    [AttributeGroupCode9]           NVARCHAR (1000) NULL,
    [AttributeGroupCode10]          NVARCHAR (1000) NULL,
    [FileKey]                       NVARCHAR (1000) NULL,
    [PrimaryResourceCode]           NVARCHAR (1000) NULL,
    [DateTime_Added]                NVARCHAR (1000) NOT NULL
);

