CREATE TABLE [dbo].[Daily_POS_Lines] (
    [File_ID]                          NVARCHAR (1000) NULL,
    [POSDocumentHeaderID]              BIGINT          NOT NULL,
    [POSDocumentHeaderCode]            NVARCHAR (1000) NULL,
    [POSDocumentLineCode]              NVARCHAR (1000) NULL,
    [LineNumber]                       BIGINT          NULL,
    [IsLeadLine]                       BIT             NULL,
    [ProductCode]                      NVARCHAR (1000) NULL,
    [DocumentLineTypeCode]             NVARCHAR (1000) NULL,
    [IsMannuallyTyped]                 BIT             NULL,
    [PriceOverrideIndicator]           BIT             NULL,
    [EmployeeDiscountIndicator]        BIT             NULL,
    [ItemQuantity]                     BIGINT          NULL,
    [ItemPrice]                        REAL            NULL,
    [ItemMeasureOrWeight]              REAL            NULL,
    [LineWeightIndicator]              BIT             NULL,
    [LineDiscountValue]                REAL            NULL,
    [LineTaxValue]                     REAL            NULL,
    [LineTotalValue]                   REAL            NULL,
    [ScannedOrKeyedItemTimestamp]      DATETIME2 (7)   NULL,
    [LineBundledIndicator]             BIT             NULL,
    [LinePromotionalDiscountIndicator] BIT             NULL,
    [PriceOverrideAmount]              REAL            NULL,
    [ResourceCodeLineApprovedBy]       NVARCHAR (1000) NULL,
    [ReceiptItemPriceRangeID]          BIGINT          NULL,
    [VoidAmount]                       REAL            NULL,
    [IsDiscount]                       BIT             NULL,
    [HeaderLineCode]                   NVARCHAR (1000) NULL,
    [AttributeLineInt1]                BIGINT          NULL,
    [AttributeLineInt2]                BIGINT          NULL,
    [AttributeLineInt3]                BIGINT          NULL,
    [AttributeLineInt4]                BIGINT          NULL,
    [AttributeLineInt5]                BIGINT          NULL,
    [AttributeLineBit1]                BIT             NULL,
    [AttributeLineBit2]                BIT             NULL,
    [AttributeLineBit3]                BIT             NULL,
    [AttributeLineBit4]                BIT             NULL,
    [AttributeLineBit5]                BIT             NULL,
    [AttributeLineBit6]                BIT             NULL,
    [AttributeLineBit7]                BIT             NULL,
    [AttributeLineBit8]                BIT             NULL,
    [AttributeLineBit9]                BIT             NULL,
    [AttributeLineBit10]               BIT             NULL,
    [AttributeGroupLineCode1]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode2]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode3]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode4]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode5]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode6]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode7]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode8]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode9]          NVARCHAR (1000) NULL,
    [AttributeGroupLineCode10]         NVARCHAR (1000) NULL,
    [FileKey]                          NVARCHAR (1000) NULL,
    [Measure1]                         REAL            NULL,
    [Measure2]                         REAL            NULL,
    [Measure3]                         REAL            NULL,
    [VoidRefundAmount]                 REAL            NULL,
    [CustomCode]                       NVARCHAR (1000) NULL,
    [Measure4]                         REAL            NULL,
    [Measure5]                         REAL            NULL,
    [Measure6]                         REAL            NULL,
    [Measure7]                         REAL            NULL,
    [Measure8]                         REAL            NULL,
    [Measure9]                         REAL            NULL,
    [Measure10]                        REAL            NULL,
    [AttributeLineBit11]               BIT             NULL,
    [AttributeLineBit12]               BIT             NULL,
    [AttributeLineBit13]               BIT             NULL,
    [AttributeLineBit14]               BIT             NULL,
    [AttributeLineBit15]               BIT             NULL,
    [AttributeLineBit16]               BIT             NULL,
    [AttributeLineBit17]               BIT             NULL,
    [AttributeLineBit18]               BIT             NULL,
    [AttributeLineBit19]               BIT             NULL,
    [AttributeLineBit20]               BIT             NULL,
    [AttributeLineInt6]                BIGINT          NULL,
    [AttributeLineInt7]                BIGINT          NULL,
    [AttributeLineInt8]                BIGINT          NULL,
    [AttributeLineInt9]                BIGINT          NULL,
    [AttributeLineInt10]               BIGINT          NULL,
    [AttributeGroupLineCode11]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode12]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode13]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode14]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode15]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode16]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode17]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode18]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode19]         NVARCHAR (1000) NULL,
    [AttributeGroupLineCode20]         NVARCHAR (1000) NULL,
    [Measure11]                        REAL            NULL,
    [Measure12]                        REAL            NULL,
    [Measure13]                        REAL            NULL,
    [Measure14]                        REAL            NULL,
    [Measure15]                        REAL            NULL,
    [Measure16]                        REAL            NULL,
    [Measure17]                        REAL            NULL,
    [Measure18]                        REAL            NULL,
    [Measure19]                        REAL            NULL,
    [Measure20]                        REAL            NULL,
    [DateTime_Added]                   NVARCHAR (1000) NOT NULL,
    [Data_Source]                      NVARCHAR (1000) NULL,
    [FileRowNumber]                    BIGINT          NULL
);

