CREATE TABLE [dbo].[Daily_POS_LoyaltyCards] (
    [File_ID]                NVARCHAR (1000) NULL,
    [POSDocumentHeaderID]    BIGINT          NULL,
    [POSDocumentHeaderCode]  NVARCHAR (1000) NULL,
    [LoyaltyCardCode]        NVARCHAR (1000) NULL,
    [LoyaltyCardNumber]      NVARCHAR (1000) NULL,
    [ScannedDateID]          BIGINT          NULL,
    [ScannedTimeID]          BIGINT          NULL,
    [ScannedTimeStamp]       DATETIME2 (7)   NULL,
    [ResourceCodeApprovedBy] NVARCHAR (1000) NULL,
    [SiteCode]               NVARCHAR (1000) NULL,
    [ShiftCode]              NVARCHAR (1000) NULL,
    [ResourceCodeCashier]    NVARCHAR (1000) NULL,
    [DiscountValue]          REAL            NULL,
    [PointValue]             REAL            NULL,
    [ManuallyTypedIndicator] BIT             NULL,
    [LoyaltyNumberID]        BIGINT          NULL,
    [FileKey]                NVARCHAR (1000) NULL,
    [AttributeBit1]          BIT             NULL,
    [AttributeBit2]          BIT             NULL,
    [AttributeBit3]          BIT             NULL,
    [AttributeBit4]          BIT             NULL,
    [AttributeBit5]          BIT             NULL,
    [AttributeGroupCode1]    NVARCHAR (1000) NULL,
    [AttributeGroupCode2]    NVARCHAR (1000) NULL,
    [AttributeGroupCode3]    NVARCHAR (1000) NULL,
    [AttributeGroupCode4]    NVARCHAR (1000) NULL,
    [AttributeGroupCode5]    NVARCHAR (1000) NULL,
    [POSDocumentLoyaltyCode] NVARCHAR (1000) NULL,
    [DateTime_Added]         NVARCHAR (1000) NOT NULL
);

