CREATE TABLE [dbo].[Daily_Inventory_Line] (
    [File_ID]                 NVARCHAR (2000) NULL,
    [FileRowNumber]           BIGINT          NULL,
    [InventoryLineCode]       NVARCHAR (2000) NULL,
    [InventoryHeaderCode]     NVARCHAR (2000) NULL,
    [DocumentLineNumber]      BIGINT          NULL,
    [ItemQuantity]            REAL            NULL,
    [ItemCostPrice]           REAL            NULL,
    [ItemRetailPrice]         REAL            NULL,
    [ProductCode]             NVARCHAR (2000) NULL,
    [UpdateDate]              DATETIME2 (7)   NULL,
    [ValidatedByCode]         NVARCHAR (2000) NULL,
    [ApprovedByCode]          NVARCHAR (2000) NULL,
    [OriginalVendorCode]      NVARCHAR (2000) NULL,
    [DocumentDate]            DATETIME2 (7)   NULL,
    [DirectionIN]             BIT             NULL,
    [DirectionOUT]            BIT             NULL,
    [ReasonCode]              NVARCHAR (2000) NULL,
    [IsMerchandise]           BIT             NULL,
    [LineCostAmount]          REAL            NULL,
    [LineRetailAmount]        REAL            NULL,
    [ReducedItemCostAmount]   REAL            NULL,
    [ReducedItemRetailAmount] REAL            NULL,
    [AttributeInt1]           BIGINT          NULL,
    [AttributeInt2]           BIGINT          NULL,
    [AttributeInt3]           BIGINT          NULL,
    [AttributeInt4]           BIGINT          NULL,
    [AttributeInt5]           BIGINT          NULL,
    [AttributeBit1]           BIT             NULL,
    [AttributeBit2]           BIT             NULL,
    [AttributeBit3]           BIT             NULL,
    [AttributeBit4]           BIT             NULL,
    [AttributeBit5]           BIT             NULL,
    [AttributeBit6]           BIT             NULL,
    [AttributeBit7]           BIT             NULL,
    [AttributeBit8]           BIT             NULL,
    [AttributeBit9]           BIT             NULL,
    [AttributeBit10]          BIT             NULL,
    [AttributeGroupCode1]     NVARCHAR (2000) NULL,
    [AttributeGroupCode2]     NVARCHAR (2000) NULL,
    [AttributeGroupCode3]     NVARCHAR (2000) NULL,
    [AttributeGroupCode4]     NVARCHAR (2000) NULL,
    [AttributeGroupCode5]     NVARCHAR (2000) NULL,
    [AttributeGroupCode6]     NVARCHAR (2000) NULL,
    [AttributeGroupCode7]     NVARCHAR (2000) NULL,
    [AttributeGroupCode8]     NVARCHAR (2000) NULL,
    [AttributeGroupCode9]     NVARCHAR (2000) NULL,
    [AttributeGroupCode10]    NVARCHAR (2000) NULL,
    [FileKey]                 NVARCHAR (2000) NULL,
    [UOM]                     REAL            NULL,
    [Measure1]                REAL            NULL,
    [Measure2]                REAL            NULL,
    [Measure3]                REAL            NULL,
    [CustomCode]              NVARCHAR (2000) NULL,
    [PrimaryResourceCode]     NVARCHAR (2000) NULL,
    [Measure4]                REAL            NULL,
    [Measure5]                REAL            NULL,
    [Measure6]                REAL            NULL,
    [Measure7]                REAL            NULL,
    [Measure8]                REAL            NULL,
    [Measure9]                REAL            NULL,
    [Measure10]               REAL            NULL,
    [AttributeBit11]          BIT             NULL,
    [AttributeBit12]          BIT             NULL,
    [AttributeBit13]          BIT             NULL,
    [AttributeBit14]          BIT             NULL,
    [AttributeBit15]          BIT             NULL,
    [AttributeBit16]          BIT             NULL,
    [AttributeBit17]          BIT             NULL,
    [AttributeBit18]          BIT             NULL,
    [AttributeBit19]          BIT             NULL,
    [AttributeBit20]          BIT             NULL,
    [AttributeGroupCode11]    NVARCHAR (2000) NULL,
    [AttributeGroupCode12]    NVARCHAR (2000) NULL,
    [AttributeGroupCode13]    NVARCHAR (2000) NULL,
    [AttributeGroupCode14]    NVARCHAR (2000) NULL,
    [AttributeGroupCode15]    NVARCHAR (2000) NULL,
    [AttributeGroupCode16]    NVARCHAR (2000) NULL,
    [AttributeGroupCode17]    NVARCHAR (2000) NULL,
    [AttributeGroupCode18]    NVARCHAR (2000) NULL,
    [AttributeGroupCode19]    NVARCHAR (2000) NULL,
    [AttributeGroupCode20]    NVARCHAR (2000) NULL,
    [AttributeInt6]           BIGINT          NULL,
    [AttributeInt7]           BIGINT          NULL,
    [AttributeInt8]           BIGINT          NULL,
    [AttributeInt9]           BIGINT          NULL,
    [AttributeInt10]          BIGINT          NULL,
    [AttributeInt11]          BIGINT          NULL,
    [AttributeInt12]          BIGINT          NULL,
    [AttributeInt13]          BIGINT          NULL,
    [AttributeInt14]          BIGINT          NULL,
    [AttributeInt15]          BIGINT          NULL,
    [DateTime_Added]          NVARCHAR (2000) NOT NULL,
    [Data_Source]             NVARCHAR (2000) NULL
);

