CREATE TABLE [dbo].[InventoryDocumentHeader_stg_bq] (
    [InventoryHeaderID]             BIGINT          NOT NULL,
    [DocumentDate]                  DATETIME        NOT NULL,
    [SiteID]                        BIGINT          NOT NULL,
    [ValidatedBy]                   BIGINT          NULL,
    [ApprovedBy]                    BIGINT          NULL,
    [DocumentNumber]                NVARCHAR (4000) NOT NULL,
    [DocumentTypeID]                BIGINT          NOT NULL,
    [UpdateDate]                    DATETIME        NULL,
    [InsertDate]                    DATETIME        NULL,
    [InventoryCountFrequencyID]     BIGINT          NULL,
    [InventoryCountTypeByProductID] BIGINT          NULL,
    [InventoryHeaderCode]           NVARCHAR (255)  NOT NULL,
    [AttributeInt1]                 BIGINT          NULL,
    [AttributeInt2]                 BIGINT          NULL,
    [AttributeInt3]                 BIGINT          NULL,
    [AttributeInt4]                 BIGINT          NULL,
    [AttributeInt5]                 BIGINT          NULL,
    [AttributeBit1]                 BIT             NULL,
    [AttributeBit2]                 BIT             NULL,
    [AttributeBit3]                 BIT             NULL,
    [AttributeBit4]                 BIT             NULL,
    [AttributeBit5]                 BIT             NULL,
    [AttributeBit6]                 BIT             NULL,
    [AttributeBit7]                 BIT             NULL,
    [AttributeBit8]                 BIT             NULL,
    [AttributeBit9]                 BIT             NULL,
    [AttributeBit10]                BIT             NULL,
    [AttributeGroupID1]             BIGINT          NULL,
    [AttributeGroupID2]             BIGINT          NULL,
    [AttributeGroupID3]             BIGINT          NULL,
    [AttributeGroupID4]             BIGINT          NULL,
    [AttributeGroupID5]             BIGINT          NULL,
    [AttributeGroupID6]             BIGINT          NULL,
    [AttributeGroupID7]             BIGINT          NULL,
    [AttributeGroupID8]             BIGINT          NULL,
    [AttributeGroupID9]             BIGINT          NULL,
    [AttributeGroupID10]            BIGINT          NULL,
    [FileKeyID]                     BIGINT          NULL,
    [PrimaryResourceID]             BIGINT          NULL
);

